name: Pathfinding
version: '${project.version}'
main: me.gxb.pathfinding.Main
authors: [ GXB ]
description: pathfinding
depend: [ ProtocolLib ]
commands:
  ph:
    description: 寻路插件
    usage: /<command> help 查看帮助
    permission: <plugin name>.ph
    permission-message: You don't have <permission>

