name: Pathfinding
version: '1.0-SNAPSHOT'
main: me.gxb.pathfinding.Main
authors: [ GXB ]
description: pathfinding
commands:
  ph:
    description: This is a demo command.
    usage: /<command>
    permission: <plugin name>.ph
    permission-message: You don't have <permission>

